package:
    name:           hiam-core
    namespace:      hiam
    label:          HIAM
    title:          Identity and Access Management server providing OAuth2, ABAC and logging
    type:           yii2-extension
    keywords:       iam, oauth2, abac, authentication, authorization, audit, yii2
    year:           2014
    description:    |
        - IAM - Identity and Access Management
        - ABAC - Attribute Based Access Control
        - Social login: Facebook, Google, VK, LinkedIn, GitHub, Live, Yandex
        - Full activity logging with searching and reporting

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
