package:
    type:           yii2-extension
    name:           hiam-core
    title:          Identity and Access Management server providing OAuth2, RBAC and logging
    headline:       HIAM
    keywords:       iam, oauth2, rbac, authentication, authorization, audit, yii2
    namespace:      hiam
    description:    |
        HIAM is Identity and Access Management server.

        Provides:

        - OAuth2 server
        - multi-factor authorization with:
            - limiting access from user allowed IPs only
            - [TOTP](https://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm) aka Google Authenticator
        - Social login: Facebook, Google, VK, LinkedIn, GitHub, Live, Yandex
        - RBAC - Role Based Access Control
        - Full activity logging with searching and reporting

        Based on:

        - [yiisoft/yii2](https://github.com/yiisoft/yii2)
        - [bshaffer/oauth2-server-php](https://github.com/bshaffer/oauth2-server-php)

